name: fib
on:
  workflow_dispatch:
  push:
    tags:
      - v1.**




jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            susamogu/FibCalc
            ghcr.io/maciejzarebski1/FibCalc
          tags: |
            type=semver,pattern={{version}}

      #Skonfigurowanie dockera + buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@master

      #Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@master

      #Konfiguracja cachowania
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      #Logowanie do Dockerhuba
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      #Logowanie do GHCR
      - name: Login to Github Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.gh_token }}

      #Zbudowanie i wypchniecie obrazu na Dockerhuba
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,src=docker.io/susamogu/buildcache
          cache-to: type=local,dest=docker.io/susamogu/buildcache
          platforms: linux/amd64, linux/arm64/v8
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
          
